config/routes.rb
Rails.application.routes.draw do
  
  namespace :api, path: '' do
    namespace :v1 do
      resources :notes do
        resources :labels, only: [:create, :destroy]
      end
    end

    namespace :v2 do
      resources :notes do
        resources :labels, only: [:create, :destroy]
      end
    end
  end

end

app/models/label.rb
class Label < ActiveRecord::Base
  has_and_belongs_to_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_and_belongs_to_many :labels

  scope :not_expired, -> { where(expire_date: nil)}
end

app/controllers/api/v1/labels_controller.rb
class Api::V1::LabelsController < ApplicationController

  def create
    note = Note.find_by_id(note_id)

    if note
      note.labels.create(name: label_name)
      render json: note.to_json(include: :labels)
    else
      render json: :no_content
    end
  end

  def destroy
    note = Note.find_by_id(note_id)

    note.labels.where(id: label_id).destroy_all

    render json: note.labels
  end

  private

  def label_id
    params[:id]
  end

  def note_id
    params[:note_id]
  end
  
  def label_name
    params.require(:label).permit(:name)
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.includes(:labels).ransack(params[:q]).result

    render json: @notes.to_json(include: :labels)
  end

  def show
    render json: @note.to_json(includes: :labels)
  end

  def new
    @note = Note.new

    render json: @note
  end

  def edit
    
    render json: @note.to_json(includes: :labels)
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      render json: @note
    else
      render json: @note.errors
    end
  end

  def update
    if @note.update(note_params)
      render json: @note
    else
      render json: @note.errors
    end
  end

  def destroy
    @note.destroy

    render json: :no_content
  end

  private
    def set_note
      @note = Note.find(params[:id])
    end

    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/api/v2/labels_controller.rb
class Api::V2::LabelsController < ApplicationController

  def create
    note = Note.find_by_id(note_id)

    if note
      note.labels.create(name: label_name)
      render json: note.to_json(include: :labels)
    else
      render json: :no_content
    end
  end

  def destroy
    note = Note.find_by_id(note_id)

    note.labels.where(id: label_id).destroy_all

    render json: note.labels
  end

  private

  def label_id
    params[:id]
  end

  def note_id
    params[:note_id]
  end
  
  def label_name
    params.require(:label).permit(:name)
  end
end

app/controllers/api/v2/notes_controller.rb
class Api::V2::NotesController < Api::V1::NotesController

  def index
    @notes = Note.not_expired.includes(:labels).ransack(params[:q]).result

    render json: @notes.to_json(include: :labels)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def create
    note = Note.find_by_id(note_id)

    if note
      note.labels.create(name: label_name)
      render json: note
    else
      render json: :no_content
    end
  end

  def destroy
    note = Note.find_by_id(note_id)

    note.labels.where(id: label_id).destroy_all

    render json: note.labels
  end

  private

  def label_id
    params[:id]
  end

  def note_id
    params[:note_id]
  end
  
  def label_name
    params.require(:label).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all

    render json: @notes
  end

  # GET /notes/1
  # GET /notes/1.json
  def show

    render json: @note
  end

  # GET /notes/new
  def new
    @note = Note.new

    render json: @note
  end

  # GET /notes/1/edit
  def edit
    
    render json: @note
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    if @note.save
      render json: @note
    else
      render json: @note.errors
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    if @note.update(note_params)
      render json: @note
    else
      render json: @note.errors
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy

    render json: :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>